* update formatting  * Update apachelog  * Add block-email  * add cpu-spike  * Add find-disabled-sites  * add maillog  * add site-enabled

diff --git a/apachelog b/apachelog
--- a/apachelog
+++ b/apachelog
@@ -1,31 +1,43 @@
 #!/bin/bash
 if [[ "$1" = "" ]];then
-	apachelog more;
+  apachelog more;
 else
-	t=$1;
-	shift;
-	case "$t" in
-		search)
-			cat /var/log/apache2/error.log | grep "$@";
-		;;
-		ignore)
-			cat /var/log/apache2/error.log | grep -v "$@";
-		;;
-		tail)
-			if [[ "$@" == "" ]];then
-				tail -f /var/log/apache2/error.log;
-			else
-				tail --lines="$@" /var/log/apache2/error.log;
-			fi;
-		;;
-		more)
-			more /var/log/apache2/error.log;
-		;;
-		flush)
-			echo "" > /var/log/apache2/error.log;
-		;;
-		*)
-			echo "Usage: $0 [{search|ignore|tail|more|flush} <params>]";
-			exit 1;
-	esac;
+  site=$1;
+  shift;
+  if [[ "$1" == "" ]];then
+    t=$site;
+    site="";
+    path="/var/log/apache2/error.log";
+  else
+    t=$1;
+    shift;
+    path="/var/log/apache2/$site.error.log";
+  fi;
+  case "$t" in
+    search)
+      cat $path | grep "$@";
+    ;;
+    ignore)
+      cat $path | grep -v "$@";
+    ;;
+    tail)
+      if [[ "$@" == "" ]];then
+        tail -f $path;
+      else
+        tail --lines="$@" $path;
+      fi;
+    ;;
+    more)
+      more $path;
+    ;;
+    flush)
+      echo "" > $path;
+    ;;
+    sites)
+      ls /var/log/apache2/*.error.log | awk '{print gensub(/\.error\.log$/, "", "g", gensub(/^.*\//, "","g"))}';
+    ;;
+    *)
+      echo "Usage: $0 <site> [{search|ignore|tail|more|flush|sites} <params>]";
+      exit 1;
+  esac;
 fi;
